server.port: 8082

spring:
  application:
    name: podcast-ms
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/podcast?useSSL=false
    username: root